// Generated by ReScript, PLEASE EDIT WITH CARE

import * as School from "School";

var me = {
  name: "Hannal",
  age: 18
};

console.log(me);

me.age = 20;

console.log(me);

console.log(me.age);

var student1 = School.student1;

student1.name = "Kay";

console.log(student1);

console.log(/* Yes */0);

function render(myColor) {
  if (myColor === "green" || myColor === "red") {
    console.log("Hello other colors");
  } else {
    console.log("Hello blue");
  }
  
}

var areYouCrushingIt = /* Yes */0;

var myColor = "red";

var myLabel = "aria-hidden";

var myNumber = 7;

export {
  me ,
  student1 ,
  areYouCrushingIt ,
  myColor ,
  myLabel ,
  myNumber ,
  render ,
  
}
/*  Not a pure module */
