// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_List from "rescript/lib/es6/belt_List.js";

console.log([
      "hello",
      "world"
    ]);

var myList = {
  hd: 1,
  tl: {
    hd: 2,
    tl: {
      hd: 3,
      tl: /* [] */0
    }
  }
};

console.log("list", myList);

var myList2 = {
  hd: 0,
  tl: myList
};

var myList3_1 = Belt_List.concat(myList, myList2);

var myList3 = {
  hd: 0,
  tl: myList3_1
};

var myList4 = Belt_List.concatMany([
      myList,
      myList2,
      myList3
    ]);

console.log(myList4);

var message = myList ? "The head of the list is the string " + (1).toString() + "and rest is " + Belt_List.toArray({
          hd: 2,
          tl: {
            hd: 3,
            tl: /* [] */0
          }
        }).toString() : "This list is empty";

console.log(message);

export {
  myList ,
  myList2 ,
  myList3 ,
  myList4 ,
  message ,
  
}
/*  Not a pure module */
