// Generated by ReScript, PLEASE EDIT WITH CARE


console.log("This red-ish");

console.log("This is red-ish");

var intl = Intl.NumberFormat("de-DE");

console.log(intl);

var myColor = "Ruby";

export {
  myColor ,
  intl ,
  
}
/*  Not a pure module */
